### ISSUE TITLE
"Edit a photo" (image downscaling?) not working in Firefox

### ISSUE THREAD

**Issue by miketaylr** [taravancil/nippler.org#1]
steps to reproduce:

1) Using Firefox (I'm on Dev Edition 51), go to https://nippler.org/
2) Upload a photo

Expected Results:
I see all the image, and can put nipples on it.

Actual Results:
I can see about 1/8th of the image.

Firefox:
<img width="1089" alt="screen shot 2016-10-12 at 1 46 14 pm" src="https://cloud.githubusercontent.com/assets/67283/19323393/52a73922-9082-11e6-93f2-9eecae6e07bc.png">

Chrome:
<img width="897" alt="screen shot 2016-10-12 at 1 46 30 pm" src="https://cloud.githubusercontent.com/assets/67283/19323411/61dfa38e-9082-11e6-9ce7-0b6d8ff14249.png">

**Comment by taravancil** [comment]
Thanks! There's definitely something funny going on with downscaling. I'm on it. Also, hi Spongebob :wave:

**Comment by taravancil** [comment]
I believe this is fixed now. Thanks again for the report and let me know if you notice anything else that's wonky.
